In [1]:
import numpy as np

In [73]:
strength = 2
ft = np.arange(1, (10 * strength) + 1, strength)
print(ft)

ft = 1 / ft
ft = ft / ft.sum()

print(ft)
print(ft.sum())

[ 1  3  5  7  9 11 13 15 17 19]
[0.4687671  0.1562557  0.09375342 0.06696673 0.05208523 0.04261519
 0.03605901 0.03125114 0.02757454 0.02467195]
1.0


In [11]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
pop_size = 10
step_size = 2

np.arange(1, (pop_size * step_size + 1), step_size)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
rotation_costs = [0, 1, 2, 3, 4, 3, 2, 1]
rot_cost_mean = sum(rotation_costs) // len(rotation_costs)

In [37]:
1*2 + 2*2 + 3*2 + 4

16

In [43]:
rotate_costs = np.roll(rotation_costs, 4 - 1)
step_rotate_cost = rotate_costs[0-1]
ft_rotate_cost = step_rotate_cost / 2.0

print(step_rotate_cost)
print(ft_rotate_cost)

4
2.0


In [51]:
population = np.random.randint(0, 9, (4, 10))
print(population)

mindx = np.random.rand(4, 10) < 0.10
print(mindx)

replacew = np.random.randint(0, 9, (4, 10))
print(replacew)

population[mindx] = replacew[mindx]
print(population)

[[0 4 7 3 1 3 7 7 6 5]
 [4 0 4 0 4 2 8 1 7 4]
 [2 2 0 2 2 0 4 5 7 3]
 [4 2 4 3 2 0 8 6 4 4]]
[[ True False False  True False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False  True]
 [False  True False False False  True False False False False]]
[[8 7 1 6 8 3 5 8 6 0]
 [0 5 7 8 2 3 8 7 7 6]
 [5 0 6 3 4 4 7 1 0 8]
 [3 4 0 5 1 2 1 7 3 7]]
[[8 4 7 6 1 3 7 7 6 5]
 [4 0 4 0 4 2 8 1 7 4]
 [2 2 0 2 2 0 4 5 7 8]
 [4 4 4 3 2 2 8 6 4 4]]


In [186]:
mut_prob = 0.05 # probability of mutation
mut_decay = 0.001
    
print(mut_prob * ((1-mut_decay)**1024))

0.017948573909485503


In [92]:
round(2.882102452392664, 5)

2.8821

In [95]:
np.round([2.882102452392664, 3.123123, 5.1252443], 6)

array([2.882102, 3.123123, 5.125244])

In [190]:
import math
math.log(2)

0.6931471805599453

In [114]:
moves = [
    (0, 0), (-1, 0), (-1, 1),
    (0, 1), (1, 1), (1, 0),
    (1, -1), (0, -1), (-1, -1),
]

# Costs of rotations.
rotation_costs = [0, 1, 2, 3, 4, 3, 2, 1]

prv = 1
nxt = 1

rotate_costs = np.roll(rotation_costs, prv - 1)
step_rotate_cost = rotate_costs[nxt - 1]

print(step_rotate_cost)

0


In [129]:
(np.array(rotation_costs) > 0).sum() / 2

3.5

In [130]:
5-12

-7

In [132]:
rng = np.random.default_rng()
splits = rng.choice(100, size=2, replace=False)
splits.sort()
print(splits)

[39 61]


In [175]:
splits = rng.choice(100, size=2, replace=False)
splits.sort()
print(splits)

[34 67]


In [134]:
splits = rng.choice(100, size=2, replace=False)
splits.sort()
print(splits)

[60 97]


In [135]:
splits = rng.choice(100, size=2, replace=False)
splits.sort()
print(splits)

[58 89]


In [136]:
splits = rng.choice(100, size=2, replace=False)
splits.sort()
print(splits)

[59 85]


In [178]:
np.full(10, np.inf).dtype

dtype('float64')

In [179]:
for xx in [1,2,3,4]:
    arama = xx ** 2
    
print(arama)

16


In [200]:
weights = [
    1.2, # w_inv_mov_loss
    1.8, # w_rotate_loss
    1.6, # w_rotate_cost
    2.4, # w_overlap_loss
    2.8, # w_spread_loss
    2.4, # w_paint_loss
]

weights /= np.array(weights).sum()

print(weights)
print(weights.sum())
print(weights.dtype)

[0.09836066 0.14754098 0.13114754 0.19672131 0.2295082  0.19672131]
1.0
float64


In [202]:
(weights * [1,2,1,2,1,2]).sum()

1.540983606557377

In [257]:
size = 5

mat = np.random.randint(0, 2, (size, size))
#mat = np.ones((size, size))
print(mat)
print()

pad = np.pad(mat, ((1,1),(1,1)), mode='constant')
#print(pad)
#print()

shift_bo = pad[0:size+0, 1:size+1]
shift_to = pad[2:size+2, 1:size+1]
shift_ri = pad[1:size+1, 0:size+0]
shift_le = pad[1:size+1, 2:size+2]
shift_bl = pad[0:size+0, 2:size+2]
shift_br = pad[0:size+0, 0:size+0]
shift_tl = pad[2:size+2, 2:size+2]
shift_tr = pad[2:size+2, 0:size+0]

density_map = shift_bo + shift_to + shift_ri + shift_le + shift_bl + shift_br + shift_tl + shift_tr

inner_size = size - 2
max_density = (3 * 4) + (5 * 4 * inner_size) + (8 * inner_size**2)
density = round(density_map.sum() / max_density, 3)

print(density)
print()

print(density_map)
print()

[[0 0 0 0 0]
 [0 0 1 0 0]
 [1 1 1 1 0]
 [0 0 1 1 1]
 [0 1 1 1 1]]

0.528

[[0 1 1 1 0]
 [2 4 3 3 1]
 [1 4 5 5 3]
 [3 6 7 7 4]
 [1 2 4 5 3]]

